apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ollama-models-pvc
  namespace: my-app
  labels:
    app: ollama
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
